
import time
import multiprocessing as mp
import asyncio
from typing import List, Any, Dict
from dataclasses import dataclass, field
from vllm import LLM, AsyncLLMEngine, SamplingParams, RequestOutput
from vllm.engine.arg_utils import AsyncEngineArgs
from transformers import AutoTokenizer, AutoConfig
import sys 
sys.dont_write_bytecode = True
from iteration_task import Task  
from iteration_producer import Producer


# # A prompt containing a large markdown table. The table is randomly generated by GPT-4.
# LONG_PROMPT = "You are a helpful assistant in recognizes the content of tables in markdown format. Here is a table as follows.\n# Table\n" + """
# | ID  | Name          | Age | Occupation    | Country       | Email                  | Phone Number   | Address                       |
# |-----|---------------|-----|---------------|---------------|------------------------|----------------|------------------------------|
# | 1   | John Doe      | 29  | Engineer      | USA           | john.doe@example.com   | 555-1234       | 123 Elm St, Springfield, IL  |
# | 2   | Jane Smith    | 34  | Doctor        | Canada        | jane.smith@example.com | 555-5678       | 456 Oak St, Toronto, ON      |
# | 3   | Alice Johnson | 27  | Teacher       | UK            | alice.j@example.com    | 555-8765       | 789 Pine St, London, UK      |
# | 4   | Bob Brown     | 45  | Artist        | Australia     | bob.b@example.com      | 555-4321       | 321 Maple St, Sydney, NSW    |
# | 5   | Carol White   | 31  | Scientist     | New Zealand   | carol.w@example.com    | 555-6789       | 654 Birch St, Wellington, NZ |
# | 6   | Dave Green    | 28  | Lawyer        | Ireland       | dave.g@example.com     | 555-3456       | 987 Cedar St, Dublin, IE     |
# | 7   | Emma Black    | 40  | Musician      | USA           | emma.b@example.com     | 555-1111       | 246 Ash St, New York, NY     |
# | 8   | Frank Blue    | 37  | Chef          | Canada        | frank.b@example.com    | 555-2222       | 135 Spruce St, Vancouver, BC |
# | 9   | Grace Yellow  | 50  | Engineer      | UK            | grace.y@example.com    | 555-3333       | 864 Fir St, Manchester, UK   |
# | 10  | Henry Violet  | 32  | Artist        | Australia     | henry.v@example.com    | 555-4444       | 753 Willow St, Melbourne, VIC|
# | 11  | Irene Orange  | 26  | Scientist     | New Zealand   | irene.o@example.com    | 555-5555       | 912 Poplar St, Auckland, NZ  |
# | 12  | Jack Indigo   | 38  | Teacher       | Ireland       | jack.i@example.com     | 555-6666       | 159 Elm St, Cork, IE         |
# | 13  | Karen Red     | 41  | Lawyer        | USA           | karen.r@example.com    | 555-7777       | 357 Cedar St, Boston, MA     |
# | 14  | Leo Brown     | 30  | Chef          | Canada        | leo.b@example.com      | 555-8888       | 246 Oak St, Calgary, AB      |
# | 15  | Mia Green     | 33  | Musician      | UK            | mia.g@example.com      | 555-9999       | 975 Pine St, Edinburgh, UK   |
# | 16  | Noah Yellow   | 29  | Doctor        | Australia     | noah.y@example.com     | 555-0000       | 864 Birch St, Brisbane, QLD  |
# | 17  | Olivia Blue   | 35  | Engineer      | New Zealand   | olivia.b@example.com   | 555-1212       | 753 Maple St, Hamilton, NZ   |
# | 18  | Peter Black   | 42  | Artist        | Ireland       | peter.b@example.com    | 555-3434       | 912 Fir St, Limerick, IE     |
# | 19  | Quinn White   | 28  | Scientist     | USA           | quinn.w@example.com    | 555-5656       | 159 Willow St, Seattle, WA   |
# | 20  | Rachel Red    | 31  | Teacher       | Canada        | rachel.r@example.com   | 555-7878       | 357 Poplar St, Ottawa, ON    |
# | 21  | Steve Green   | 44  | Lawyer        | UK            | steve.g@example.com    | 555-9090       | 753 Elm St, Birmingham, UK   |
# | 22  | Tina Blue     | 36  | Musician      | Australia     | tina.b@example.com     | 555-1213       | 864 Cedar St, Perth, WA      |
# | 23  | Umar Black    | 39  | Chef          | New Zealand   | umar.b@example.com     | 555-3435       | 975 Spruce St, Christchurch, NZ|
# | 24  | Victor Yellow | 43  | Engineer      | Ireland       | victor.y@example.com   | 555-5657       | 246 Willow St, Galway, IE    |
# | 25  | Wendy Orange  | 27  | Artist        | USA           | wendy.o@example.com    | 555-7879       | 135 Elm St, Denver, CO       |
# | 26  | Xavier Green  | 34  | Scientist     | Canada        | xavier.g@example.com   | 555-9091       | 357 Oak St, Montreal, QC     |
# | 27  | Yara Red      | 41  | Teacher       | UK            | yara.r@example.com     | 555-1214       | 975 Pine St, Leeds, UK       |
# | 28  | Zack Blue     | 30  | Lawyer        | Australia     | zack.b@example.com     | 555-3436       | 135 Birch St, Adelaide, SA   |
# | 29  | Amy White     | 33  | Musician      | New Zealand   | amy.w@example.com      | 555-5658       | 159 Maple St, Wellington, NZ |
# | 30  | Ben Black     | 38  | Chef          | Ireland       | ben.b@example.com      | 555-7870       | 246 Fir St, Waterford, IE    |
# """

# def get_generation_time(llm: LLM, sampling_params, prompts):
#     # time the generation
#     start_time = time.time()
#     output = llm.generate(prompts, sampling_params=sampling_params)
#     end_time = time.time()
#     # print the output and generation time
#     print(f"Output: {output[0].outputs[0].text}")
#     print(f"Generation time: {end_time - start_time} seconds.")

# # set enable_prefix_caching=True to enable APC
# llm = LLM(
#     model='lmsys/longchat-13b-16k',
#     enable_prefix_caching=True
# )

# sampling_params = SamplingParams(temperature=0, max_tokens=100)


# # Querying the age of John Doe
# get_generation_time(
#     llm,
#     sampling_params,
#     LONG_PROMPT + "Question: what is the age of John Doe? Your answer: The age of John Doe is ",
# )

# # Querying the age of Zack Blue
# # This query will be faster since vllm avoids computing the KV cache of LONG_PROMPT again.
# get_generation_time(
#     llm,
#     sampling_params,
#     LONG_PROMPT + "Question: what is the age of Zack Blue? Your answer: The age of Zack Blue is ",
# )



# ========== 初始化 vLLM 引擎 ==========
async def init_engine(model_path: str) -> AsyncLLMEngine:
    engine_args = AsyncEngineArgs(
        model=model_path,
        tokenizer=model_path,
        dtype="float16",
        gpu_memory_utilization=0.9,
    )
    engine = await AsyncLLMEngine.from_engine_args(engine_args)
    return engine

# ========== 消费者逻辑 ==========
async def vllm_executor(
    task_queue: asyncio.Queue,
    preloaded_tasks: List[Task],
    engine: AsyncLLMEngine,
    params: SamplingParams,
):
    while True:
        _, _, taskID = await task_queue.get()

        if taskID is None:
            task_queue.task_done()
            break

        task: Task = preloaded_tasks[taskID]

        async for output in engine.generate(
            prompt=task.prompt,
            params=params,
            request_id=str(taskID),
        ):
            if output.finished:
                task.response = output.outputs[0].text
                print(f"[DONE] Task {taskID}: {task.response}")
                break

        task_queue.task_done()

# # ========== Pipeline 主函数 ==========
# async def run_pipeline(preloaded_tasks: List[Task], producer: Producer, model_path: str):
#     # 初始化任务和队列
#     task_queues = [asyncio.Queue(), asyncio.Queue()]

#     # Engine & Sampling 参数
#     engine = await init_engine(model_path)
#     sampling_params = SamplingParams(
#         temperature=0.7,
#         top_p=0.95,
#         max_tokens=128,
#     )

#     # 启动 Producer & Consumer
#     await asyncio.gather(
#         producer.produce_async(task_queues, preloaded_tasks),
#         vllm_executor(task_queues[-1], preloaded_tasks, engine, sampling_params),
#     )

#     return preloaded_tasks

# ========== 实际调用 ==========
if __name__ == "__main__":
    mp.set_start_method("spawn", force=True)
    import os 

    async def main():
        os.environ["TOKENIZERS_PARALLELISM"] = "false"
        # ✅ 请在这里定义你的 prompt 数据集
        arrival_rate = 10       # 每秒到达的任务数
        retrain_rate = 0.0      # 重训练率
        n_test_samples = 100    # 测试样本数
        strategy = "sync"       # 调度策略
        arrival_pattern = "poisson"     # 到达模式
        model_path = "mistralai/Mistral-7B-Instruct-v0.2"  # 模型路径
        data_path = "data/StanfordNLP"  # 数据集路径
        tokenizer = AutoTokenizer.from_pretrained(model_path, padding_side="left", use_fast=True)
        if tokenizer.pad_token is None:
            tokenizer.pad_token = tokenizer.eos_token
            tokenizer.pad_token_id = tokenizer.eos_token_id
        max_context_length = AutoConfig.from_pretrained(model_path).max_position_embeddings

        # Get producer (loading dataset)
        producer = Producer(
            arrival_rate=arrival_rate, 
            retrain_rate=retrain_rate, 
            n_test_samples=n_test_samples,
            strategy=strategy,
            arrival_pattern=arrival_pattern, 
        )
        preloaded_tasks = producer.load_dataset(
            tokenizer=tokenizer,
            max_length=max_context_length,
            dataset_name=data_path,
        )

        # 启动整个 pipeline
        # results = await run_pipeline(preloaded_tasks, producer, model_path)
        # 初始化任务和队列
        task_queues = [asyncio.Queue(), asyncio.Queue()]

        # Engine & Sampling 参数
        engine = await init_engine(model_path)
        sampling_params = SamplingParams(
            temperature=0.7,
            top_p=0.95,
        )

        # 启动 Producer & Consumer
        await asyncio.gather(
            producer.produce_async(task_queues, preloaded_tasks),
            vllm_executor(task_queues[-1], preloaded_tasks, engine, sampling_params),
        )

        print("\n=== Final Results ===")
        for task in preloaded_tasks:
            print(f"Task {task.taskID}: {task.response.strip()}")

    asyncio.run(main())
    # loop = asyncio.new_event_loop()
    # asyncio.set_event_loop(loop)
    # loop.run_until_complete(main())
